{
    "How to Analyze Crypto": "VALUE",
    "What’s DAO?": "N/A",
    "Ton voices live": "I LOVE BLUM",
    "Forks Explained": "GO GET",
    "Secure your Crypto!": "BEST PROJECT EVER",
    "Navigating Crypto": "HEYBLUM",
    "What are Telegram Mini Apps?": "CRYPTOBLUM",
    "Say No to Rug Pull!": "SUPERBLUM",
    "Liquidity Pools Guide": "BLUMERSSS",
    "$2.5M+ DOGS Airdrop": "HAPPYDOGS",
    "Doxxing? What's that?": "NODOXXING",
    "Pre-Market Trading?": "WOWBLUM",
    "Play Track and Type Track Name": "BLUM – BIG CITY LIFE",
    "How to Memecoin?": "MEMEBLUM",
    "Token Burning: How & Why?": "ONFIRE",
    "Bitcoin Rainbow Chart": "SOBLUM",
    "Crypto Terms. Part 1": "BLUMEXPLORER",
    "How to Trade Perps?": "CRYPTOFAN",
    "Sharding Explained": "BLUMTASTIC",
    "DeFi Explained": "BLUMFORCE",
    "How To Find Altcoins?": "ULTRABLUM",
    "Crypto Slang. Part 1": "BLUMSTORM",
    "What is On-chain Analysis?": "BLUMEXTRA",
    "Pumptober Special": "PUMPIT",
    "DeFi Risks: Key Insights": "BLUMHELPS",
    "Crypto Slang. Part 2": "FOMOOO",
    "What’s Crypto DEX?": "DEXXX",
    "Choosing a Crypto Exchange": "CRYPTOZONE",
    "Node Sales in Crypto": "BLUMIFY",
    "Understanding Gas Fees": "CRYPTOGAS",
    "What is Slippage?": "CRYPTOBUZZ",
    "What’s Next for DeFi?": "BLUMNOW",
    "Smart Contracts 101": "SMARTBLUM",
    "Crypto Slang. Part 3": "BOOBLUM",
    "Regulation: Yay or Nay?": "BLUMSSS",
    "DEX History": "GODEX",
    "Crypto Regulations #2": "BLUMRULES",
    "P2P Trading Safety Tips": "BLUMTIPS",
    "Crypto Communities": "BLUMMUNITY",
    "Dec 6 Crypto News": "HUNDRED",
    "Dex Evolution": "BLUMSPARK",
    "Crypto Slang. Part 4": "LAMBOBLUM",
    "What Are AMMs?": "CRYPTOSMART",
    "Memepad Tutorial": "MEMEPAD",
    "DEX History #3": "LOVEBLUM",
    "Blum CMO @ Blockchain Life": "BLUMISLIFE",
    "Is Binance a DEX?": "BLUMIES",
    "Crypto Slang. Part 5": "GONNABLUM",
    "Crypto in Everyday Life": "BLUMANCE",
    "Trade any memecoin": "N/A",
    "Launch a memecoin": "N/A",
  "How to analyze crypto?": "VALUE",
  "Forks Explained": "GO GET",
  "Secure your Crypto": "BEST PROJECT EVER",
  "Navigating crypto": "HEYBLUM",
  "What are Telegram Mini Apps?": "CRYPTOBLUM",
  "Say No to Rug Pull!": "superblum",
  "What Are AMMs?": "CRYPTOSMART",
  "Liquidity Pools Guide": "BLUMERSSS",
  "$2.5M+ DOGS Airdrop": "HAPPYDOGS",
  "Doxxing? What's that?": "NODOXXING",
  "Pre-Market Trading?": "WOWBLUM",
  "Play Track & type track...": "blum - big city life",
  "How to Memecoin?": "MEMEBLUM",
  "Token Burning: How & Why?": "ONFIRE",
  "Bitcoin Rainbow Chart?": "SOBLUM",
  "Crypto Terms. Part 1": "BLUMEXPLORER",
  "How to trade Perps?": "CRYPTOFAN",
  "Sharding Explained": "BLUMTASTIC",
  "DeFi Explained": "BLUMFORCE",
  "How To Find Altcoins?": "ULTRABLUM",
  "What's On-chain analysis?": "Blumextra",
  "Pumptober Special": "Pumpit",
  "DeFi Risks: Key insights": "Blumhelps",
  "Crypto Slang. Part 2": "FOMOOO",
  "Choosing a Crypto Exchange": "CRYPTOZONE",
  "Node Sales in Crypto?": "Blumify",
  "What Crypto Dex?": "DEXXX",
  "Understanding Gas fees": "Cryptogas",
  "What is Slippage?": "Cryptobuzz",
  "What’s Next for DeFi?": "BLUMNOW",
  "Smart Contracts 101": "Smartblum",
  "Crypto Slang. Part 3": "BOOBLUM",
  "Regulation: Yay or...": "Blumsss",
  "DEX History": "Godex",
  "Crypto Regulation #2": "Blumrules",
  "P2P Trading Safety Tips": "BLUMTIPS",
  "Crypto Communities": "Blummunity",
  "is Binance a Dex?": "Blumies",
  "Dec 6 Crypto News": "Hundred",
  "Task: Dex Evolution": "Blumspark",
  "Crypto Slang. Part 4": "LAMBOBLUM",
  "Memepad Tutorial": "Memepad",
  "DEX History #3": "LOVEBLUM",
  "Dec 12 News": "RIPPLE",
  "Dec 13 News": "BITCOINJESUS",
  "Blum CMO @ Blockchain Life": "BLUMISLIFE",
  "Dec 16 News": "BITCOIN",
  "Crypto in Everyday Life": "Blumance",
  "Dec 17 News": "KENDRICK",
  "Dec 18 News": "Mark",
  "Crypto Slang. Part 5": "GONNABLUM",
  "What is Uniswap?": "BLUMSHINE
}
